"""Check that the port reads every piece of The Nightjar's content the way the
original engine would.

Loads the 14 levels with the port's loader, then checks everything the data
refers to: properties, triggers, messages, agents, levels and sounds.  Every
oddity is one of the original's own data defects, with its reason - or it is
unexplained, which means a gap in the port's understanding, and the check
fails.

Writes CONTENT_CHECK.md next to the executable (docs/ when run from source).
"""

from __future__ import annotations

import os
import sys

if __package__ in (None, ''):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from nightjar.assets import audit                               # noqa: E402
from nightjar.util import console, paths                        # noqa: E402


def report(r) -> str:
    c = r['counts']
    lines = ['# Content check', '',
             'Generated by `apps/check_content.py`.  Every finding is one of the '
             "original's own data defects, explained, or the check fails.", '',
             f"{c['levels']} levels, {c['objects']} objects, {c['triggers']} triggers, "
             f"{c['sound refs']} sound references, {c['declarations']} playlist "
             'declarations.', '',
             f"Explained: {len(r['explained'])}.  Unexplained: {len(r['unexplained'])}.", '',
             '| level | kind | what | why |', '|---|---|---|---|']
    for kind, level, what, _detail in r['explained']:
        why = audit.KNOWN[(kind, level, what)]
        lines.append(f'| {level} | {kind} | `{what}` | {why} |')
    for kind, level, what, detail in r['unexplained']:
        lines.append(f'| {level} | {kind} | `{what}` | **UNEXPLAINED** {detail} |')
    return '\n'.join(lines) + '\n'


def main(rep) -> int:
    rep.show('The Nightjar - game content check')
    rep.show('=' * 46)
    bundle = paths.game_bundle()
    r = audit.run(bundle)
    c = r['counts']
    rep.show(f"levels {c['levels']}, objects {c['objects']}, triggers {c['triggers']}, "
             f"sound refs {c['sound refs']}, declarations {c['declarations']}")
    if paths.FROZEN:
        out = os.path.join(paths.writable_root(), 'CONTENT_CHECK.md')
    else:
        out = os.path.join(paths.resource_root(), 'docs', 'CONTENT_CHECK.md')
    with open(out, 'w', encoding='utf-8') as fh:
        fh.write(report(r))
    rep.show(f'report written to {out}')
    if r['unexplained']:
        for f in r['unexplained']:
            rep.show(f'  UNEXPLAINED  {f}')
        rep.say(f"Content check failed: {len(r['unexplained'])} findings have no explanation.")
        return 1
    rep.say(f"Content check passed. {c['levels']} levels read; "
            f"{len(r['explained'])} oddities, every one explained.")
    return 0


if __name__ == '__main__':
    raise SystemExit(console.run(main))
