"""Who observes and who posts each engine message, and which ones the levels use.

Built on calls.py's resolved call sites.  An observer is an
addObserver:selector:name:object: whose name argument is the message; a poster
is any postNotificationName:* / notificationWithName:* call carrying it.

    python msgmap.py  -> docs/MESSAGE_MAP.md
"""
import json
import re
from collections import defaultdict
from pathlib import Path

from calls import load, walk

HERE = Path(__file__).resolve().parent
APP = HERE.parent / 'reference' / 'Payload' / 'Papa Sangre II.app'


def level_messages():
    """message name (normalised to PGE_MESSAGE_*) -> set of levels firing it."""
    used = defaultdict(set)
    for f in sorted((APP / 'levels' / 'papasangre2').glob('*.json')):
        d = json.loads(f.read_text(encoding='utf-8'))
        for L in d['layers']:
            for o in L.get('objects') or []:
                for k, v in (o.get('properties') or {}).items():
                    if not k.startswith('On'):
                        continue
                    for st in str(v).split('|'):
                        st = st.strip()
                        if not st:
                            continue
                        name = st.split(':')[0].strip()
                        if not name.startswith('PGE_MESSAGE_'):
                            name = 'PGE_MESSAGE_' + name
                        used[name].add(f.stem)
    return used


def main():
    funcs = load()
    observe = defaultdict(list)
    post = defaultdict(list)
    for fn, lines in funcs.items():
        for addr, sel, args, fargs, callee in walk(lines):
            s = sel.replace('SEL:', '')
            names = [a[2:-1] for a in args if a and a.startswith('@"')]
            if s.startswith('addObserver:selector:name:'):
                for n in names:
                    observe[n].append((fn, (args[1] or '?').replace('SEL:', ''), addr))
            elif s.startswith(('postNotificationName:', 'notificationWithName:')):
                for n in names:
                    post[n].append((fn, s, addr))
    used = level_messages()
    allmsgs = sorted(set(observe) | set(post) | set(used))
    out = ['# Message map (Papa Sangre II binary)\n',
           'Generated by `tools/msgmap.py` from `dis/calls.txt`. For each message: '
           'the levels whose triggers fire it, the observers that register for it '
           '(with the handler selector) and the methods that post it.\n',
           'A level message with **no observer** is a no-op in the original: a '
           'misspelling, or a message this engine version never implemented.\n',
           '## Messages fired by level data\n',
           '| message | levels | observers |', '|---|---|---|']
    for m in allmsgs:
        if m in used:
            obs = ', '.join('`%s`->`%s`' % (fn, h) for fn, h, _ in observe.get(m, [])) or '**NONE**'
            out.append('| `%s` | %d: %s | %s |' % (m, len(used[m]), ' '.join(sorted(used[m])), obs))
    out.append('\n## Every message in the binary\n')
    for m in allmsgs:
        if not m.startswith(('PGE_', 'PPAE_', 'S3D')):
            continue
        out.append('### `%s`\n' % m)
        if m in used:
            out.append('* fired by level data in: %s' % ' '.join(sorted(used[m])))
        for fn, h, a in observe.get(m, []):
            out.append('* observed by `%s` -> `%s` (%s)' % (fn, h, a))
        for fn, how, a in post.get(m, []):
            out.append('* posted by `%s` via `%s` (%s)' % (fn, how, a))
        out.append('')
    dst = HERE.parent / 'docs' / 'MESSAGE_MAP.md'
    dst.write_text('\n'.join(out), encoding='utf-8')
    print('wrote', dst)
    # the same facts as data, for the port's content check
    mod = ['"""GENERATED by tools/msgmap.py from the Papa Sangre II disassembly - do not edit.',
           '',
           'Every message name some class registers an observer for',
           '(`addObserver:selector:name:object:`), with the registering method and the',
           'handler selector. A level message not in here reaches nobody in the original.',
           '"""', '', 'OBSERVED = {']
    for m in sorted(observe):
        mod.append('    %r: %r,' % (m, sorted({(fn, h) for fn, h, _ in observe[m]})))
    mod.append('}')
    target = HERE.parent / 'papasangre2' / 'assets' / 'observed.py'
    target.write_text('\n'.join(mod) + '\n', encoding='utf-8')
    print('wrote', target)


if __name__ == '__main__':
    main()
